services:
  frontend:
    image: frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    restart: always
    command: sh -c "pnpm i sharp && npx next telemetry disable && pnpm run build && pnpm start"